version: "3"
services:
  ai:
    build: AI
    network_mode: host
    environment:
      - PYTHONUNBUFFERED=1
  backend:
    build: backend
    network_mode: host
    environment:
      - PYTHONUNBUFFERED=1
  frontend:
    build:
      context: frontend
    network_mode: host
    depends_on:
      - backend  
  