version: "3"
services:
  ai:
    build: AI
    network_mode: host
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
  backend:
    build: backend
    network_mode: host
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: frontend
    network_mode: host
    depends_on:
      - backend  
  