version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  celery:
    build: .
    command: celery -A app.celery_worker worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app  # Ensure the same volume is mounted to see the same files

  redis:
    image: "redis:alpine"
